{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "%matplotlib inline"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "\n# Error handling\n\nWe show how errors are handled within ``dman``.\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Introduction\nTo run the example you will need the following imports:\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "from dataclasses import dataclass\nimport sys\nfrom tempfile import TemporaryDirectory\nimport traceback\nimport dman\nfrom dman import tui\nfrom dman import log\n\n# turn off warnings\nlog.default_config(level=log.CRITICAL)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Since `dman` is designed to store results generated by experiments, it \nalways attempts to store as much information as possible. This implies \nthat exceptions are handled internally. Often such exceptions \ncan occur when encountering unserializable types.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "@dataclass\nclass Address:\n    street: str\n    number: int\n    zip_code: int\n    city: str\n    country: str\n\n    def __str__(self):\n        return f'{self.street} {self.number}, {self.zip_code} {self.city}, {self.country}'\n\nhome = Address('Kasteelpark Arenberg', 10, 3001, 'Leuven', 'Belgium')\nemployee = {'name': 'John Doe', 'home': home}\n\ndman.save('employee', employee)\ntui.walk_directory(dman.mount('employee'), show_content=True)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "As you can see only the serializable parts of the data structure were stored. \nThe address has been replaced with a specification of the issue encountered.\nWhen we load the employee from disk again we get the following:\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "recovered = dman.load('employee')\nprint(recovered['home'])"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Usually a warning is raised when serialization fails:\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "with dman.log.logger_context(level=log.WARNING):\n    dman.serialize(employee)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "The warning will tell you where the serialization failed. In this case \nit specifies `@dict.Address` to indicate that the `Address` object \nwas stored in a dictionary. \n\n<div class=\"alert alert-info\"><h4>Note</h4><p>If you do want an exception thrown you can do get one as follows:\n\n```python\ntry:\n    dman.serialize(employee, context=dman.BaseContext(validate=True))\nexcept dman.ValidationError as e:\n    msg = traceback.format_exception(*sys.exc_info())\n    print(''.join(msg))\n```\n      This is only recommended during debugging, since it interrupts \n      serialization while it is in progress and can therefore result \n      in loss of large amounts of data.</p></div>\n\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Usually the log messages should provide enough information to \nfix any issues. We nonetheless continue this example with more \ndetailed examples describing the different things that can go wrong during \nserialization and what you can expect as output. \nWe also illustrate how data can be recovered even if initial errors \nwere present in the implementation.\n\nWe will be doing so in terms of the fundamental datastructures involved \nin `dman`. To understand how these fit into the bigger picture \ntake a look at the other examples.\n\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Serializables\nSerialization\n^^^^^^^^^^^^^^^^^\n\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "We first serialize an unserializable type:\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "class Base:\n    ...\n\n\nser = dman.serialize(Base())\ntui.print_serialized(ser)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Next let's try serialization of an object with an erroneous implementation\nof `__serialize__`.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "@dman.serializable(name=\"base\")\nclass Base:\n    def __serialize__(self):\n        raise RuntimeError(\"Invalid implementation\")\n\n    @classmethod\n    def __deserialize__(cls, ser):\n        ...\n\n\nser = dman.serialize(Base())\ntui.print_serialized(ser)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "After deserialization we can still view the traceback resulting in the exception:\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "err = dman.deserialize(ser)\nprint(err)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "We also detect `__serialize__` methods with invalid signatures.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "@dman.serializable(name=\"base\")\nclass Base:\n    # `__serialize__` should either have no or two arguments besides `self`.\n    def __serialize__(self, arg1, arg2):\n        return 'Base'\n\n    @classmethod\n    def __deserialize__(cls, ser):\n        raise RuntimeError('Invalid implementation')\n\n\nser = dman.serialize(Base())\ntui.print_serialized(ser)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### Deserialization\nNow we move on to deserialization.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "@dman.serializable(name=\"base\")\nclass Base:\n    def __serialize__(self):\n        return '<base>'\n\n    @classmethod\n    def __deserialize__(cls, ser):\n        raise RuntimeError('Invalid implementation')\n\n\nser = dman.serialize(Base())\ntui.print_serialized(ser)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Even though the serialized object is valid, we cannot recover the object.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "err = dman.deserialize(ser)\nprint(err)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Note how the error contains information about what was serialized.\nThe error is serializable.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "ser = dman.serialize(err)\ntui.print_serialized(ser)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Moreover when we try to deserialize it again, now with a valid \nclass definition, things work. This sometimes allows for data restoration.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "@dman.serializable(name=\"base\")\nclass Base:\n    def __serialize__(self):\n        return '<base>'\n\n    @classmethod\n    def __deserialize__(cls, ser):\n        return cls()\n\nbase = dman.deserialize(ser)\nprint(base)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## Records\n\nSince a `record` is also serializable it should suppress errors as well\nsuch that the data structure is not damaged by a single erroneous item.\nWe provide an overview of the errors that typically occur \nand how they are represented within the result of the serialization.\n\nLet's begin with a storable class that cannot write to disk\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "@dman.storable(name='base')\nclass Base:\n    def __write__(self, path: str):\n        raise RuntimeError('Cannot write to disk.')\n\n    @classmethod\n    def __read__(cls, path: str):\n        return cls()\n\nrec = dman.record(Base())"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "If we try to serialize the object without a context we run into some issues\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "ser = dman.serialize(rec)\ntui.print_serialized(ser)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "And when serializing it with a context we run into another.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "root = TemporaryDirectory()\nctx = dman.Context.from_directory(root.name)\nser = dman.serialize(rec, context=ctx)\ntui.print_serialized(ser)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "When we cannot write instead then we get the following behavior:\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "@dman.storable(name='base')\nclass Base:\n    def __write__(self, path: str):\n        with open(path, 'w') as f:\n            f.write('<base>')\n\n    @classmethod\n    def __read__(cls, path: str):\n        raise RuntimeError('Cannot read from disk.')\n\nrec = dman.record(Base(), preload=True)\nser = dman.serialize(rec, context=ctx)\ntui.print_serialized(ser)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "When deserializing we get the following.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "dser = dman.deserialize(ser, context=ctx)\nprint(dser)\nprint(dser.content)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Note how the contents are still unloaded. We could fix `Base` and try loading \nagain. We also simulate a more advanced scenario where we first serialize \nthe invalid record again, reproducing what would happen \nif objects became invalid and the remainder of the data structure \nwas saved to disk again. We also define a corrected version of `Base`.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "ser = dman.serialize(dser, context=ctx)\ntui.print_serialized(ser)\ntui.walk_directory(root.name, show_content=True, console=tui.Console(width=200))\n\n@dman.storable(name='base')\nclass Base:\n    def __write__(self, path: str):\n        with open(path, 'w') as f:\n            f.write('<base>')\n\n    @classmethod\n    def __read__(cls, path: str):\n        return cls()"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "Now we can load the contents of the original invalid record.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "print(dser.content)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "And we can load the contents of the one that was serialized when\nit was invalid.\n\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "dser = dman.deserialize(ser, context=ctx)\nprint(dser)\nprint(dser.content)"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.10.9"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}